### ISSUE TITLE
ml-gradle 5.0.0 does not work with gradle 7.6.3

### ISSUE THREAD

**Issue by peetkes** [marklogic/ml-gradle#714] opened 2024-09-20 09:44 UTC
I tried running the gradle mlNewProject with the ml-gradle 5.0.0 plugin but got a concurrency issue
I ran below command and got the following error.
```
$ gradle mlNewProject

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'testApp'.
> java.util.concurrent.ExecutionException: org.gradle.api.GradleException: Failed to create Jar file /Users/kester/.gradle/caches/jars-9/21f503c55fdde83d51a4f784631b641e/jackson-core-2.17.2.jar.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 641ms
```

I upgraded to gradle 7.6.4 and that did the trick.

**Comment by rjrudin** [comment] 2024-09-20 12:12
Thanks @peetkes - this has been an ongoing issue in Gradle itself - https://stackoverflow.com/questions/77225378/gradle-clean-fails-with-gradleexception-failed-to-create-jar-file - and the bump from Jackson 2.15.x to 2.17.2 in ml-gradle 5.0.0 appears to have triggered another scenario where Gradle is buggy. According to that SO post, the issue is completely resolved in Gradle 8.5. But I verified what you encountered, which is that 7.6.4 addresses this particular issue. 

I'll update the README accordingly. Thanks again for the report.

**Closed by rjrudin** 2024-09-20 12:12 UTC
